/*
 * MouseEvents_Bubbling
 * 
 * MouseEvents and KeyEvents move through the display list
 * in Nest in a manner similar to the event flow
 * in ActionScript 3: they enter the display list from the
 * NestSpriteContainer and proceed downward to the NestSprites at the
 * bottom (front) of the display list, and then bubble back up
 * the display list.
 * 
 * This allows developers to place mouse/key handlers on parent
 * NestSprites that respond to events generated by interacting
 * with their children.  It also offers the opportunity
 * to handle events in the event capture phase, to manually
 * stop propagation of an event, and to query the event target
 * and currentTarget, all in a way similar to ActionScript 3.0.
 * 
 * For more information on the event flow, read up on it here:
 * http://adobe.ly/eventflow
 */

import com.transmote.nest.*;
import com.transmote.nest.events.*;

NestSpriteContainer spriteContainer;
int numSprites = 30;

void setup () {
  size(260, 610);
  setupSprites();
}

void draw () {
  background(0);
  spriteContainer.update();
}

void setupSprites () {
  // create a NestSpriteContainer to hold all other NestSprites.
  spriteContainer = new NestSpriteContainer(this);
  
  RectSprite s0 = new RectSprite();
  s0.x = 10;
  s0.y = 10;
  
  RectSprite s0_0 = new RectSprite();
  s0_0.x = 50;
  s0_0.y = 50;
  RectSprite s0_1 = new RectSprite();
  s0_1.x = 50;
  s0_1.y = 100;
  
  RectSprite s0_1_0 = new RectSprite();
  s0_1_0.x = 50;
  s0_1_0.y = 50;
  RectSprite s0_1_1 = new RectSprite();
  s0_1_1.x = 50;
  s0_1_1.y = 100;
  
  RectSprite s0_2 = new RectSprite();
  s0_2.x = 50;
  s0_2.y = 250;
  
  RectSprite s0_2_0 = new RectSprite();
  s0_2_0.x = 50;
  s0_2_0.y = 50;
  RectSprite s0_2_1 = new RectSprite();
  s0_2_1.x = 50;
  s0_2_1.y = 100;
  RectSprite s0_2_2 = new RectSprite();
  s0_2_2.x = 50;
  s0_2_2.y = 150;
  
  RectSprite s0_2_2_0 = new RectSprite();
  s0_2_2_0.x = 50;
  s0_2_2_0.y = 50;
  RectSprite s0_2_2_1 = new RectSprite();
  s0_2_2_1.x = 50;
  s0_2_2_1.y = 100;
  
  RectSprite s0_2_2_1_0 = new RectSprite();
  s0_2_2_1_0.x = 50;
  s0_2_2_1_0.y = 50;
  
  spriteContainer.addChild(s0);
  s0.addChild(s0_0);
  s0.addChild(s0_1);
  s0.addChild(s0_2);
  s0_1.addChild(s0_1_0);
  s0_1.addChild(s0_1_1);
  s0_2.addChild(s0_2_0);
  s0_2.addChild(s0_2_1);
  s0_2.addChild(s0_2_2);
  s0_2_2.addChild(s0_2_2_0);
  s0_2_2.addChild(s0_2_2_1);
  s0_2_2_1.addChild(s0_2_2_1_0);
  
  // try uncommenting these, one at a time,
  // to interrupt event handling and bubbling.
  //s0_2_2.inputChildren = false;
  //s0_2_2.inputEnabled = false;
}
